Repository teawan-Noh/eventcafecloud, pull requests merged in 2022-07, with the labels that each got.

#35 Feature/login
  src/main/java/com/eventcafecloud/cafe/controller/CafeController.java
  src/main/java/com/eventcafecloud/cafe/domain/Cafe.java
  src/main/java/com/eventcafecloud/cafe/domain/CafeReview.java
  src/main/java/com/eventcafecloud/cafe/domain/CafeReviewStatus.java
  src/main/java/com/eventcafecloud/cafe/dto/CafeReviewRequestDto.java
  src/main/java/com/eventcafecloud/cafe/repository/CafeReviewRepository.java
  src/main/java/com/eventcafecloud/cafe/service/CafeService.java
  src/main/java/com/eventcafecloud/common/UserArgumentResolver.java
  src/main/java/com/eventcafecloud/config/WebConfig.java
  src/main/java/com/eventcafecloud/config/security/SecurityConfig.java
  src/main/java/com/eventcafecloud/oauth/domain/UserPrincipal.java
  src/main/java/com/eventcafecloud/oauth/domain/UserPrincipalForResolver.java
  src/main/java/com/eventcafecloud/oauth/filter/TokenAuthenticationFilter.java
  src/main/java/com/eventcafecloud/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/eventcafecloud/oauth/service/CustomUserDetailsService.java
  src/main/java/com/eventcafecloud/oauth/token/AuthToken.java
  src/main/java/com/eventcafecloud/oauth/token/AuthTokenProvider.java
  src/main/java/com/eventcafecloud/post/dto/PostReadResponseDto.java
  src/main/java/com/eventcafecloud/post/dto/PostStatusUpdateRequestDto.java
  src/main/java/com/eventcafecloud/post/service/PostService.java
  src/main/java/com/eventcafecloud/user/controller/AdminController.java
  src/main/java/com/eventcafecloud/user/controller/AuthController.java
  src/main/java/com/eventcafecloud/user/controller/MainController.java
  src/main/java/com/eventcafecloud/user/controller/ProfileController.java
  src/main/java/com/eventcafecloud/user/controller/hostProfileController.java
  src/main/java/com/eventcafecloud/user/domain/User.java
  src/main/resources/templates/admin/admin-cafe.html
  src/main/resources/templates/admin/admin-post.html
  src/main/resources/templates/admin/fragments/manage-cafe.html
  src/main/resources/templates/admin/fragments/manage-post.html
  src/main/resources/templates/cafeReview.html
  src/main/resources/templates/myPage.html
  src/main/resources/templates/profile-host/fragments/hostUserInfo.html
  src/main/resources/templates/profile-host/host-userInfo.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/profile/fragments/userInfo.html
  src/main/resources/templates/profile/fragments/userUpdateModal.html
  src/main/resources/templates/profile/profile-userInfo.html
  src/main/resources/templates/profile/userInfo.html
Labels: enhancement

#66 Feature/cafe
  src/main/java/com/eventcafecloud/cafe/controller/CafeApiController.java
  src/main/java/com/eventcafecloud/cafe/controller/CafeController.java
  src/main/java/com/eventcafecloud/cafe/domain/CafeOptionType.java
  src/main/java/com/eventcafecloud/cafe/domain/CafeReview.java
  src/main/java/com/eventcafecloud/cafe/domain/CafeReviewStatus.java
  src/main/java/com/eventcafecloud/cafe/dto/CafeCreateRequestDto.java
  src/main/java/com/eventcafecloud/cafe/dto/CafeDetailResponseDto.java
  src/main/java/com/eventcafecloud/cafe/dto/CafeReviewResponseDto.java
  src/main/java/com/eventcafecloud/cafe/repository/CafeRepository.java
  src/main/java/com/eventcafecloud/cafe/repository/CafeReviewRepository.java
  src/main/java/com/eventcafecloud/cafe/service/CafeService.java
  src/main/java/com/eventcafecloud/cafe/sort/CreatedDateDesc.java
  src/main/java/com/eventcafecloud/cafe/sort/PriceAsc.java
  src/main/java/com/eventcafecloud/cafe/sort/PriceDesc.java
  src/main/java/com/eventcafecloud/cafe/sort/SortStrategy.java
  src/main/java/com/eventcafecloud/exception/ExceptionStatus.java
  src/main/resources/static/css/cafeDetail.css
  src/main/resources/static/css/cafeReview.css
  src/main/resources/static/css/card.css
  src/main/resources/static/js/cafe/cafeList.js
  src/main/resources/static/js/cafe/cafeReview.js
  src/main/resources/templates/cafe/cafeDetail.html
  src/main/resources/templates/cafe/cafeList.html
  src/main/resources/templates/cafe/createCafeForm.html
  src/main/resources/templates/cafeReview.html
  src/main/resources/templates/fragments/header.html
Labels: enhancement

#95 Feature/cafe
  src/main/java/com/eventcafecloud/cafe/controller/CafeApiController.java
  src/main/java/com/eventcafecloud/cafe/controller/CafeController.java
  src/main/java/com/eventcafecloud/cafe/domain/Cafe.java
  src/main/java/com/eventcafecloud/cafe/service/CafeService.java
  src/main/java/com/eventcafecloud/event/repository/EventRepository.java
  src/main/java/com/eventcafecloud/exception/Error.java
  src/main/java/com/eventcafecloud/s3/S3Service.java
  src/main/resources/static/css/cafeDetail.css
  src/main/resources/static/js/cafe/cafeDelete.js
  src/main/resources/static/js/cafe/cafeReview.js
  src/main/resources/templates/admin/admin-cafe.html
  src/main/resources/templates/admin/fragments/manage-cafe.html
  src/main/resources/templates/cafe/cafeDetail.html
  src/main/resources/templates/cafe/createCafeForm.html
  src/main/resources/templates/profile-host/fragments/cafes.html
  src/main/resources/templates/profile-host/host-cafes.html
Labels: bug, enhancement

#107 Feature/cafe
  src/main/java/com/eventcafecloud/cafe/service/CafeService.java
  src/main/resources/application.yml
  src/main/resources/static/css/myPosts.css
  src/main/resources/templates/cafe/createCafeForm.html
  src/main/resources/templates/cafe/updateCafeForm.html
  src/main/resources/templates/error/500.html
Labels: bug

#145 Feature/cafe 카페 수정 api 본인 글에만 요청가능하도록 수정, 달력 이벤트 클릭시 상세페이지로 이동 등
  src/main/java/com/eventcafecloud/cafe/controller/CafeController.java
  src/main/java/com/eventcafecloud/cafe/dto/CafeCalenderInfoResponseDto.java
  src/main/java/com/eventcafecloud/cafe/dto/CafeListResponseDto.java
  src/main/java/com/eventcafecloud/cafe/dto/CafeUpdateRequestDto.java
  src/main/java/com/eventcafecloud/cafe/service/CafeService.java
  src/main/resources/static/css/cafeDetail.css
  src/main/resources/static/css/card.css
  src/main/resources/static/css/footer.css
  src/main/resources/static/js/cafe/cafeList.js
  src/main/resources/static/js/cafe/calenderApi.js
  src/main/resources/static/js/logout.js
  src/main/resources/templates/cafe/cafeDetail.html
  src/main/resources/templates/cafe/cafeList.html
  src/main/resources/templates/cafe/createCafeForm.html
  src/main/resources/templates/cafe/updateCafeForm.html
  src/main/resources/templates/cafeReview.html
  src/main/resources/templates/event/createEventForm.html
  src/main/resources/templates/event/eventDetail.html
  src/main/resources/templates/event/eventList.html
  src/main/resources/templates/event/fragments/event-detail.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/mainHeader.html
  src/main/resources/templates/index.html
  src/main/resources/templates/post/createPostForm.html
  src/main/resources/templates/post/editPostForm.html
  src/main/resources/templates/post/postDetail.html
  src/main/resources/templates/post/userBoard.html
Labels: enhancement
